### ISSUE TITLE
Some changese made for ESP boards

### ISSUE THREAD

**Issue by gmos** [m2m-solutions/M2M_Logger#3]
Adapted library to work on ESP8266 and ESP32.  Added setter for flush-timeout.
Can be pulled from https://gitlab.com/Remcoo/m2m_logger.git

Tested it on ESP32 (bare wrover), ESP8266 (ESP-12 4MB) and  ATSAMD21 (Sodaq Explorer).

By the way:
  - the %t format specifier used in the example is not a standard and is ignored on the ESP boards but works on the ATSAMD21.
  - the while(serial) in the example is required on the Sodaq, but hangs the ESP8266. Better to include a timeout in the loop.
 -  the library in the Arduino Library manager is an old version..

**Comment by bergdahl** [comment]
Thanks.
